import streamlit as st
import json
import os

REPORT_PATH = "docs/doc_coverage_report.json"

st.set_page_config(
    page_title="AI Legacy Modernization",
    layout="wide"
)

st.title("🧠 AI-Powered Legacy Code Modernization")

st.markdown(
    """
This dashboard provides **visibility into AI-driven legacy Java modernization**.
It shows **coverage, health indicators, and traceability metrics** generated by the agent pipeline.
"""
)

# ---------------- Load Coverage ----------------

def load_report():
    if os.path.exists(REPORT_PATH):
        with open(REPORT_PATH, encoding="utf-8") as f:
            return json.load(f)
    return None


report = load_report()

# ---------------- Metrics ----------------

if report:
    st.subheader("📊 Coverage Summary")

    col1, col2, col3 = st.columns(3)

    col1.metric(
        "Classes Covered",
        f"{report['classes_covered_in_doc']} / {report['total_classes_in_ir']}",
        f"{report['class_coverage_percent']}%"
    )

    col2.metric(
        "Methods Covered",
        f"{report['methods_covered_in_doc']} / {report['total_methods_in_ir']}",
        f"{report['method_coverage_percent']}%"
    )

    col3.metric(
        "Overall Health",
        "✅ Good" if report["method_coverage_percent"] >= 60 else "⚠ Needs Improvement"
    )
else:
    st.warning("No coverage data found. Run the pipeline first.")

# ---------------- Navigation Hint ----------------

st.markdown("---")
st.info(
    """
📘 **Navigation**
Click the ☰ (top-left menu) to open the sidebar and navigate to:
- Documentation
- IR Viewer
- Parsed Java Files
"""
)
